/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/Layouts/AppHeader.vue')['default']
    Apps: typeof import('./src/components/Apps.vue')['default']
    AppSidebar: typeof import('./src/components/Layouts/AppSidebar.vue')['default']
    DesktopLayout: typeof import('./src/components/Layouts/DesktopLayout.vue')['default']
    EmptyState: typeof import('./src/components/ui/EmptyState.vue')['default']
    EventTabs: typeof import('./src/components/EventTabs.vue')['default']
    EventWorkspaceHeader: typeof import('./src/components/EventWorkspaceHeader.vue')['default']
    MobileAppHeader: typeof import('./src/components/Mobile/MobileAppHeader.vue')['default']
    MobileLayout: typeof import('./src/components/Layouts/MobileLayout.vue')['default']
    MobileSidebar: typeof import('./src/components/Mobile/MobileSidebar.vue')['default']
    Notifications: typeof import('./src/components/Notifications.vue')['default']
    PageHeader: typeof import('./src/components/ui/PageHeader.vue')['default']
    QrScanner: typeof import('./src/components/QrScanner.vue')['default']
    QuickAction: typeof import('./src/components/ui/QuickAction.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarLink: typeof import('./src/components/SidebarLink.vue')['default']
    StatCard: typeof import('./src/components/ui/StatCard.vue')['default']
    StatusBadge: typeof import('./src/components/ui/StatusBadge.vue')['default']
    ToastNotification: typeof import('./src/components/ToastNotification.vue')['default']
    UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
  }
}
